console.log(/^.(\sC|OW|\s)+$/.test("NOW C"));
console.log(/^.{3}[COPE\s]+$/.test("NOW C"));
console.log(/^[RACE]+(AS|KS)$/.test("RACKS"));
console.log(/^[RAYS]+C(KS|SK|Y)$/.test("RACKS"));
console.log(/^[NOA\sE]+$/.test(" A NO"));
console.log(/^[\sAP]+[M-W]{2}$/.test(" A NO"));
console.log(/^(BL|UF)[A\s,HE]+$/.test("BLE H"));
console.log(/^[A-Q]{2}[^PASH]+.$/.test("BLE H"));
console.log(/^[A-G][ARTH\s.]+$/.test("EART."));
console.log(/^(IR|T\.|EA|R)+$/.test("EART."));
console.log(/^[\sEA]+G[OD\s]+$/.test(" GOOD"));
console.log(/^[^APE][DOG]+$/.test(" GOOD"));
console.log(/^(IG|\sN|H\s|H)+$/.test(" NIGH"));
console.log(/^\W[GINES]+.?$/.test(" NIGH"));
console.log(/^(SW|EA|T,\s)+$/.test("T, SW"));
console.log(/^[\sWEAT,S']+$/.test("T, SW"));
console.log(/^(H|M|E)\1T[\sPYS]+$/.test("EET P"));
console.log(/^(.?)\1(P|T\s)+$/.test("EET P"));
console.log(/^[O-Z][ICE\s]+.+[PEN]$/.test("RINCE"));
console.log(/^(IN|R|CE|\sP)+$/.test("RINCE"));
console.log(/^(NR\s|BE)+.+$/.test("NR BE  TER"));
console.log(/^[BRIN\W]{4}[TERN\s]+$/.test("NR BE  TER"));
console.log(/^[^SPYC\s]+$/.test("OAALAGN,EI"));
console.log(/^(LA|O|AA){2,3}.+$/.test("OAALAGN,EI"));
console.log(/^[^ADSP]+$/.test("WC EROI TN"));
console.log(/^[A-EQ-Z]{2}['\s!]E[^.!Y]+$/.test("WC EROI TN"));
console.log(/^[^BLUCE]+.$/.test(" KN TOGS C"));
console.log(/^\W(KN|\s|\sK)+TO.+$/.test(" KN TOGS C"));
console.log(/^[^AYN\s]+(E|A)$/.test("CSOH.DHWPE"));
console.log(/^[^GAULE,]+D[^OL]+$/.test("CSOH.DHWPE"));