console.log(/^[^DO.HY:PER!']+$/.test("ALAS, "));
console.log(/^(A|E|I|O).\1[SOFT,]+.$/.test("ALAS, "));
console.log(/^[ROPE\s]+[YE\s]+$/.test("POOR Y"));
console.log(/^[PAST]{1}(O|U|T)+[YEAR\s]+$/.test("POOR Y"));
console.log(/^[FAST\s,OR]+.*$/.test("ORICK!"));
console.log(/^O[RICE]+(S\?|K!)$/.test("ORICK!"));
console.log(/^[^FOUR,SHE]+$/.test(" ... A"));
console.log(/^[\s.!]+[ASH]$/.test(" ... A"));
console.log(/^[LEAF\s]*[M-R]+$/.test(" FELLO"));
console.log(/^[^PLAY?KIS]+[LOVE]*$/.test(" FELLO"));
console.log(/^[^TRASH]+$/.test("W OF I"));
console.log(/^(\sI|W\s|OF)+$/.test("W OF I"));
console.log(/^[NITRO,FUN]+$/.test("NFINIT"));
console.log(/^(N|O).(I|F)\1\2.$/.test("NFINIT"));
console.log(/^(A|E|I)[J\s]+\1(BE|ST)$/.test("E JEST"));
console.log(/^(S\s|E\s).[EAST]+$/.test("E JEST"));
console.log(/^[POLEA\s]{5}[^ASH]+$/.test("APO  WNE"));
console.log(/^[^IR]{2}[OWN\s]+.$/.test("APO  WNE"));
console.log(/^.(OR|AP|IE).[FA\sT]+$/.test("LOR.F F "));
console.log(/^[LORD'.]+(PS|F\s)+$/.test("LOR.F F "));
console.log(/^[^ELFR]+(E|OI|J)+$/.test("AOI.EOIJ"));
console.log(/^[A?OH–FIRE.]+J?$/.test("AOI.EOIJ"));
console.log(/^[^OH,AI\s:IM!]+$/.test("SRC.LFNE"));
console.log(/^(SR|LF|C.)+[END]+$/.test("SRC.LFNE"));
console.log(/^[KLIPS,CLAP\s]+$/.test(", K L IS"));
console.log(/^[^YOAS]+L[\sHIS]+$/.test(", K L IS"));
console.log(/^[\sHY:!;]+.+(T|A|PE)\1$/.test(" Y!AOITT"));
console.log(/^[^EAR;][IF:A?YOLK!].+$/.test(" Y!AOITT"));