console.log(/^['2B']?(O|R)?['\2BINGE']+$/.test("'NIB"));
console.log(/^(\W)?(\1)?[HONEYPOTS]+$/.test("THOSE"));
console.log(/^[WAFT\s]{3,5}[WINNIE]+$/.test("TFA  W"));
console.log(/^[THI\s]+(S|I|NG|ER\s){3,5}$/.test("TH ISNG"));
console.log(/^[BOOK\s]+(O|F)?(Z|E|N)+$/.test("BEEEEEEE"));
console.log(/^(O|H)(.)[BROTH3R]+(\2)(HO|BS)+$/.test("O RR HO"));
console.log(/^(.)[STORY]+(I|SE|E)(\1)+$/.test(" STE  "));
console.log(/^[ANOTHER]*[KINGDOM\s]{1,5}$/.test("KING "));
console.log(/^(\W)?(O|R)?[BLACK\.RAVEN]+$/.test("VNR."));
console.log(/^(KV|A|VK)(\W)(B|EE|PO|O|H)+$/.test("VK OB"));
console.log(/^(\w){3}(\W)(WE|A|R|E)*[THE]{2}$/.test("NIS ET"));
console.log(/^(R|U|N){2}(T|O)[THEORY\.]+$/.test("RNTREHT"));
console.log(/^\.?[REG]{4}(V|\s)[FIT]{2}$/.test(".GERE FT"));
console.log(/^(\W){1,3}[A'FRIENDHIP]+$/.test("   EIAH'"));
console.log(/^(\W){1,3}[CON\sP1RASHE]+$/.test(" HES ON"));
console.log(/^(\w){1,3}(\W)+[HISTORY?]+$/.test("OEN SI"));
console.log(/^(TH|E){1,3}(W|IN|G|ED)+(\W|EB)+$/.test("EGWEB"));
console.log(/^\W[BIT]{1}[BITT3R]+(TH|AN)*$/.test("'TTTB"));
console.log(/^(A|N)?(\w)?(F|I|B)?(\2)(EO|NS)?$/.test("NHFHEO"));
console.log(/^(I|O|NS){2}[AND](.)[SEA](\2)+$/.test("IOA E  "));
console.log(/^[B0S\s]{3}(I|N)(SK|R|I|B|E)+$/.test("BS IERSK"));
console.log(/^(E\W|ER)+[PERSP3CTIVE\s]+$/.test("E SERTIV"));
console.log(/^[^EIN](.)(.)(\W)(\2)(\1)(\5)$/.test("WNE ENN"));
console.log(/^(OR|G)+(T|H|E)*(\W)[BRIDGER]+$/.test("GEH GR"));
console.log(/^[JOKE]{1,3}[\W1TH]{1,5}$/.test("EO  ."));