console.log(/(N3|TRA|N7)+/.test("TRAN7"));
console.log(/[^OLD\s]+/.test("TRAN7"));
console.log(/[1LOVE2?4]+./.test("24L? "));
console.log(/(\d+)[LA\s$?]+/.test("24L? "));
console.log(/(A|D)M[5-8$L]+/.test("AM5$L"));
console.log(/(\-P|5\$|AM|Z|L)+/.test("AM5$L"));
console.log(/[^\s0ILAD]+/.test("-WE3O"));
console.log(/(\-D|\-WE)+[^L4-9N$?]+/.test("-WE3O"));
console.log(/[B-E]+(.)\1./.test("DEFF?"));
console.log(/[FED$?]+/.test("DEFF?"));
console.log(/[2TAIL\-D]+/.test("T2A-D"));
console.log(/[^ILYO]+/.test("T2A-D"));
console.log(/(WE|R4|RY|M)+/.test("R4MWE"));
console.log(/.+[MURDEW]+/.test("R4MWE"));
console.log(/[FEAL3-5S]+/.test("AL5EF"));
console.log(/[1ALF5$E\s]+/.test("AL5EF"));
console.log(/[^FA\sT1-2]+F/.test("N?$3F"));
console.log(/[\dFAN$?]+/.test("N?$3F"));
console.log(/[LO\s\?5-8]+/.test("7 L ?"));
console.log(/.+\s.+\?/.test("7 L ?"));